-- MySQL Script generated by MySQL Workbench
-- Sat Oct  8 12:12:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `cpf` VARCHAR(50) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idcategoria` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto_cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto_cadastro` (
  `idproduto_cadastro` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `categoria` INT NOT NULL,
  PRIMARY KEY (`idproduto_cadastro`),
  INDEX `categoria_idx` (`categoria` ASC) VISIBLE,
  CONSTRAINT `categoria`
    FOREIGN KEY (`categoria`)
    REFERENCES `mydb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lista_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lista_compra` (
  `idlista_compra` INT NOT NULL,
  `produto_cadastro` INT NOT NULL,
  `valor_total` DECIMAL(5,2) NOT NULL,
  `usuario_cpf` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idlista_compra`),
  INDEX `usuario_cpf_idx` (`usuario_cpf` ASC) VISIBLE,
  CONSTRAINT `usuario_cpf`
    FOREIGN KEY (`usuario_cpf`)
    REFERENCES `mydb`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lista_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lista_produto` (
  `id_lista` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `preco` DECIMAL(5,2) NOT NULL,
  `quantidade` VARCHAR(45) NOT NULL,
  INDEX `id_produto_idx` (`id_produto` ASC) VISIBLE,
  INDEX `id_lista_idx` (`id_lista` ASC) VISIBLE,
  CONSTRAINT `id_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `mydb`.`produto_cadastro` (`idproduto_cadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_lista`
    FOREIGN KEY (`id_lista`)
    REFERENCES `mydb`.`lista_compra` (`idlista_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
